path: /home/c/cchatzip/Desktop/Waste_Segregation/data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: PET
  1: HDPE
  2: PP
  3: PS
  4: Metal