path: /home/cchatzip/Desktop/Theses_files/Waste_Segregation/data # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')
test: images/test # test images (relative to 'path')

# Classes
names:
  0: PET
  1: HDPE
  2: PP
  3: PS
  4: Metal