path: '/content/gdrive/My Drive/ODyolo_AddedMetalCategory'  # dataset root dir
train: data/images/train  # train images (relative to 'path')
val: data/images/val  # val images (relative to 'path')

# Classes
names:
  0: PET
  1: HDPE
  2: PP
  3: PS
  4: Metal